### ISSUE TITLE
채팅방 구현

### ISSUE THREAD

**Issue by Leejha** [osamhack2021/WEB_Untact_Operation_Comand_UOC#5]
webRTC로 채팅방을 구현하게 되면 뭐가 다른가?

socket.io방식으로 하면 되는거 아닌가?

peer to peer가 연결되어있으면 굳이 socket을 안써도 채팅이 가능한가?

**Comment by dpfprtus** [comment]
더 알아봐야 하는 부분인것 같습니다.

**Comment by zeroshift01** [comment]
ㄹㅇㄴㄴㅇㄻ

**Comment by zeroshift01** [comment]
시작에서 끝까지 완성
