### ISSUE TITLE
git push오류

### ISSUE THREAD

**Issue by dpfprtus** [osamhack2021/WEB_Untact_Operation_Comand_UOC#6]
1. 커밋을 하고 나서 github의 오류인지 뭔지 잘은 모르겠지만 github에 commit이 반영이 되기까지 대략 10분정도가 소요되는 현상이 발생하였다.  이 딜레이가 있는 도중에 다른 팀원이 git pull을 하고나서 git push를 하려고 하니까 **git merge오류**가 발생하였다.

**Comment by Leejha** [comment]
git reset으로 해결
