### ISSUE TITLE
TimeIssue

### ISSUE THREAD

**Issue by Leejha** [osamhack2021/WEB_Untact_Operation_Comand_UOC#8]
fullcallendar 에 event.start가 들어갈 때 Date 마지막에 Z가 붙으면서 ex)2021-09-27T09:30:00.000Z
내가 지정한 시간과 실제로 나타나는 시간이 달라지는 문제가 있음

**Comment by dpfprtus** [comment]
image
타임존 이슈인데 Date 객체를 한국시간으로 변환해주는 작업 해줘야된다고하니 사진 참고하십쇼
